### PR TITLE
docs: Deployment guide for GitLab Pages

### PR DESCRIPTION
**Pull request by stranger26**
#266 #246 

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you are merging your commits to `master` branch.
* [x] Add some descriptions and refer relative issues for you PR.
* [x] DO NOT include files inside lib directory.

### CODE REVIEW

**Comment by QingWei-Li** [comment]
Thanks!

**Comment by stranger26** [comment]
Just checked the live site, the `?>` seems to be not working, or is did I use the wrong syntax?

**Comment by QingWei-Li** [comment]
Can you provide a demo? Or do you use the same as below?
https://docsify.js.org/#/helpers?id=general-tips

**Comment by stranger26** [comment]
https://docsify.js.org/#/deploy Check out the second line for GitLab Pages

**Comment by QingWei-Li** [comment]
fixed.
Missing a blank line

**Pull request merged**
