### PR TITLE
Create vue.rtl.css

### PR DESCRIPTION
**Pull request by mrfarhadir**
adding rtl version for vue template

### CODE REVIEW

**Comment by QingWei-Li** [comment]
Hi @mrfarhadir 
sorry for the late reply. I think it only needs to code a little style can solve, do not need to add a new theme. So you do not support each theme, this is too bloated.

**Comment by mrfarhadir** [comment]
@QingWei-Li 
Thanks for your reply, I was started to create rtl version for dark theme too it was almost finished !
ok now I will create a rtl.css to support all themes.
and I have another question which is not related to rtl issue , for better SEO it's good to have ! after # in urls , will you add this feather ?

**Comment by QingWei-Li** [comment]
@mrfarhadir 
I would also like to better support SEO, but unfortunately I can not do so. The current docsify is a SPA project that itself is not friendly to SEO support. Perhaps you can try the SSR feature. Or you can use other static compiled document tools, such as githook.

**Comment by mrfarhadir** [comment]
Thanks You @QingWei-Li

**Pull request closed without merging**
