### PR TITLE
Add JS MythBusters to showcase

### PR DESCRIPTION
**Pull request by Kikobeats**
I migrated from docpress, very happy!

Not related question, but I don't know why search is not enabled:
https://github.com/Kikobeats/js-mythbusters/blob/master/docs/index.html#L27

### CODE REVIEW

**Comment by QingWei-Li** [comment]
You forgot to install the search plugin. 😊

```html
<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
<!-- here -->
<script src="//unpkg.com/docsify/lib/plugins/search.min.js"></script>
```

https://docsify.js.org/#/plugins?id=full-text-search

**Comment by Kikobeats** [comment]
oh thanks!

**Comment by jrappen** [comment]
@Kikobeats

Btw you could also extend `docsify` with [KaTeX](https://github.com/Khan/KaTeX) for the math sections in your docs should you want to extend those:

> ⚠️ order matters below!

```html
<!-- index.html -->

...

  <link rel="stylesheet" href="//unpkg.com/katex/dist/katex.min.css">
  <link rel="stylesheet" href="//unpkg.com/docsify/lib/themes/vue.css">

...

<script src="//unpkg.com/katex/dist/katex.min.js"></script>
<script src="//unpkg.com/docsify/lib/docsify.min.js"></script>

<!-- docsify plug-ins after docsify main -->

...

```

**Comment by Kikobeats** [comment]
oh, thanks! Could be awesome if you can convert this into a PR 😄

**Pull request merged**
